#!/usr/bin/env sh
#
# Join two videos side by side for visual comparison.  Unlike "compare-videos",
# this script tries to do it fast.
#
# Usage:
#
# compare-videos-fast video-1.mp4 video-2.mp4 output.mp4

ffmpeg -i $1 -i $2 \
  -filter_complex '[0:v]pad=iw*2:ih[int];[int][1:v]overlay=W/2:0[vid]' \
  -map [vid] \
  -preset fast \
  $3
