#!/usr/bin/env sh
#
# Apply motion stabilization to a video.  Requires ffmpeg to be compiled with
# vid.stab.
#
# Usage:
#
# smooth-video input.mp4 output.mp4

set -e

SHAKY_INPUT_VIDEO=$1
SMOOTH_OUTPUT_VIDEO=$2

ffmpeg -i $SHAKY_INPUT_VIDEO \
    -vf vidstabdetect=stepsize=6:shakiness=10:accuracy=15:result=transform_vectors.trf -f null -

ffmpeg -i $SHAKY_INPUT_VIDEO -vf \
    vidstabtransform=input=transform_vectors.trf:zoom=1:smoothing=30 \
    -tune film -b:v 25M -vcodec libx264 -acodec copy -y $SMOOTH_OUTPUT_VIDEO.mp4
